services:

  backend:
    image: 2201409/infra-backend
    container_name: nonprofit_backend
    env_file:
      - ../backend/.env
    ports:
      - "8080:8080"
    volumes:
      - chroma_data:/app/chroma_db
    networks:
      - nonprofit_network
    restart: unless-stopped

  frontend:
    image: 2201409/infra-frontend
    container_name: nonprofit_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nonprofit_network
    restart: unless-stopped

volumes:
  chroma_data:

networks:
  nonprofit_network: