# ---------- BUILD STAGE ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copy only package files first (better caching)
COPY package.json package-lock.json* ./

# Install deps
RUN npm install

# Copy rest of frontend code
COPY . .

# Build app
RUN npm run build


# ---------- PRODUCTION STAGE ----------
FROM nginx:alpine

# Copy built files to nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]