- name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: 15.207.184.18
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      cd /home/ubuntu/Non-Profit-AI-System

      # Pull latest code (VERY IMPORTANT)
      git pull origin main

      # Create .env dynamically
      echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > backend/.env

      cd infra

      # Pull images (no build)
      sudo docker-compose pull

      # Stop old containers
      sudo docker-compose down || true

      # Clean unused containers
      sudo docker container prune -f

      # Start containers (NO BUILD)
      sudo docker-compose up -d