name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build & Push Backend
        run: |
          docker build -t 2201409/infra-backend:latest \
                 -t 2201409/infra-backend:${IMAGE_TAG} \
                 ./backend -f infra/Dockerfile.backend
          docker push 2201409/infra-backend:latest
          docker push 2201409/infra-backend:${IMAGE_TAG}

      - name: Build & Push Frontend
        run: |
          docker build -t 2201409/infra-frontend:latest \
                 -t 2201409/infra-frontend:${IMAGE_TAG} \
                 ./frontend -f infra/Dockerfile.frontend
          docker push 2201409/infra-frontend:latest
          docker push 2201409/infra-frontend:${IMAGE_TAG}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 15.207.184.18
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
           cd /home/ubuntu/Non-Profit-AI-System

           git reset --hard
           git pull origin main

           echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > backend/.env

           cd infra
           sudo docker-compose down
           sudo docker-compose pull
           sudo docker-compose up -d --force-recreate